name: pdf
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install TeX
        run: sudo apt-get update && sudo apt-get -y install texlive-full
      - name: Compile
        run: latexmk -pdf -silent -shell-escape main.tex
