name: monograph verification

on:
  push:
    branches: [ main, rh-dev, '**' ]
    paths:
      - problems/**
      - .github/workflows/rh-ci.yml
      - preamble.tex
  pull_request:
    paths:
      - problems/**
      - preamble.tex

jobs:
  latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install TeX Live
        run: sudo apt-get update && sudo apt-get -y install texlive-full
      - name: Compile monograph (log captured)
        id: compile
        continue-on-error: true
        run: |
          latexmk -pdf -interaction=nonstopmode -file-line-error -halt-on-error clay-problems/main.tex 2>&1 | tee build.log
      - name: Tail build log on failure
        if: steps.compile.outcome == 'failure'
        run: tail -n 200 build.log
      - name: Upload build log
        uses: actions/upload-artifact@v4
        with:
          name: rh-build-log
          path: build.log
      - name: Fail if LaTeX build failed
        if: steps.compile.outcome == 'failure'
        run: exit 1

  lean:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Lean via elan script
        run: |
          sudo apt-get update -y && sudo apt-get install -y curl
          curl -L https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh | bash -s -- -y
          echo "${HOME}/.elan/bin" >> $GITHUB_PATH
      - name: Check Lean stubs (RH, NS)
        run: |
          lean clay-problems/problems/RH/rh_lean/Ledger.lean
          lean clay-problems/problems/NS/ns_lean/Energy.lean
          lean clay-problems/problems/YM/ym_lean/AxialPositivity.lean
      - name: Run PvsNP gadget checker
        run: python clay-problems/problems/PvsNP/pnp_checker.py 